version: 2.1

jobs:
  check-node:
    parameters:
      tag:
        type: string
        default: '2.7.4-browsers'
    docker:
      - image: cimg/ruby:<< parameters.tag >>
    steps:
      - run:
          name: Check Node
          command: |
            # https://github.com/nodejs/docker-node/issues/1149#issuecomment-552705885
            which node
            node -v

workflows:
  main:
    jobs:
      - check-python:
          matrix:
            parameters:
              tag:
                - 2.7.4-browsers
                - 3.0.2-browsers
