version: 2.1

jobs:
  check-python:
    parameters:
      tag:
        type: string
        default: '2.7.4-browsers'
    docker:
      - image: cimg/ruby:<< parameters.tag >>
    steps:
      - run:
          name: Check Python
          command: |
            which python
            python --version

workflows:
  main:
    jobs:
      - check-python:
          matrix:
            parameters:
              tag:
                - 2.7.4-browsers
                - 3.0.2
